spring:
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        format_sql: true
logging:
  level:
    web: debug
    dev.idion.bladitodo: debug
    org.hibernate.SQL: debug

---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:todo;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    initialization-mode: embedded
  h2:
    console:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/todo?useUnicode=yes&characterEncoding=UTF-8
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
  flyway: # https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#common-application-properties-data-migration 참고
    baseline-on-migrate: true # 비어있지 않은 db schema를 migration할 때, baseline을 사용할 것인지 여부
    baseline-version: 1 # 이 버전 이후로 마이그레이션을 진행한다.
    baseline-description: 기본 스키마 # baseline 적용시 기존 스키마에 태그를 지정

---

spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:mysql://bladi-todo-db.cr55utyiscde.ap-northeast-2.rds.amazonaws.com:3306/todo?useUnicode=yes&characterEncoding=UTF-8
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway: # https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#common-application-properties-data-migration 참고
    baseline-on-migrate: true # 비어있지 않은 db schema를 migration할 때, baseline을 사용할 것인지 여부
    baseline-version: 1 # 이 버전 이후로 마이그레이션을 진행한다.
    baseline-description: 기본 스키마 # baseline 적용시 기존 스키마에 태그를 지정
logging:
  level:
    web: info
