spring:
  profiles:
    active: dev
logging:
  level:
    web: debug
    dev.idion.bladitodo: debug
    org.hibernate.SQL: debug

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:bladi-todo
    username: sa
    password:
    initialization-mode: embedded
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

---

spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

---

spring:
  config:
    activate:
      on-profile: production
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    web: info
