spring:
  profiles:
    active: dev
logging:
  level:
    web: debug
    dev.idion.bladitodo: debug
    org.hibernate.SQL: debug

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:bladi-todo
    username: sa
    password:
    initialization-mode: embedded
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/todo?useUnicode=yes&characterEncoding=UTF-8
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

---

spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:mysql://bladi-todo-db.cr55utyiscde.ap-northeast-2.rds.amazonaws.com:3306/todo?useUnicode=yes&characterEncoding=UTF-8
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    web: info
