spring:
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        format_sql: true
logging:
  level:
    web: debug
    dev.idion.bladitodo: debug
    org.hibernate.SQL: debug

---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:todo;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    initialization-mode: embedded
  h2:
    console:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/todo?useUnicode=yes&characterEncoding=UTF-8
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate

---

spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:mysql://bladi-todo-db.cr55utyiscde.ap-northeast-2.rds.amazonaws.com:3306/todo?useUnicode=yes&characterEncoding=UTF-8
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    web: info
